apiVersion: v1
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        # kapp.k14s.io/update-strategy: always-replace
        storageclass.kubernetes.io/is-default-class: "false"
      name: nfs-provisioner
    parameters:
      fsType: ext4
      iopsPerGB: "10"
      type: gp2
    provisioner: kubernetes.io/aws-ebs
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
